from SimplePipes.pipe import Pipe
from typing import Any, Literal

@Pipe
def out(x: Any) -> Any: ...
@Pipe
def utf(x: str, encoding: Literal[8] | Literal[16] | Literal[32] = ...) -> bytes: ...

mkset: Pipe = ...
mkdict: Pipe = ...
mklist: Pipe = ...
mktuple: Pipe = ...
